const $ = (q, root = document) => root.querySelector(q);
const $$ = (q, root = document) => [...root.querySelectorAll(q)];
const desktop = $('#desktop');
const startMenu = $('#startMenu');
const APP_TARGETS = { system:'system', jasper:'jasper', terminal:'terminal', research:'kernel', files:'services', network:'services', settings:'system', services:'services', boot:'boot', kernel:'kernel', aurora:'aurora', 'aurora boot':'aurora-boot' };
const APP_PROGRESS = new Map();
const history = [];
let historyIndex = 0;
const BOOT_STAGES = [[13,'Spitfire loader'],[25,'Hardware discovery'],[38,'Memory fabric'],[50,'Koronos kernel'],[63,'System services'],[75,'Jasper desktop manager'],[88,'Wayland compositor'],[100,'Aurora desktop READY']];
function toggleStart(force){if(!startMenu)return;const open=force??!startMenu.classList.contains('open');startMenu.classList.toggle('open',open);startMenu.setAttribute('aria-hidden',String(!open));if(open)setTimeout(()=>$('#startSearch')?.focus(),60);}
function ensureProgress(win){let bar=win.querySelector('.app-progress');if(!bar){bar=document.createElement('div');bar.className='app-progress';bar.setAttribute('role','progressbar');bar.setAttribute('aria-label','Application startup progress');const fill=document.createElement('span');fill.className='app-progress-fill';const label=document.createElement('b');label.className='app-progress-text';label.textContent='0%';bar.append(fill,label);win.querySelector('.titlebar')?.after(bar);}return bar;}
function setProgress(win,value,state='running'){const bar=ensureProgress(win),v=Math.max(0,Math.min(100,Number(value)||0));bar.dataset.state=state;bar.querySelector('.app-progress-fill').style.width=`${v}%`;bar.querySelector('.app-progress-text').textContent=`${Math.round(v)}%`;bar.setAttribute('aria-valuenow',String(Math.round(v)));}
function activateWindow(name){const raw=String(name||'').trim().toLowerCase(),targetName=APP_TARGETS[raw]||raw;if(!targetName)return false;const target=document.querySelector(`[data-window="${CSS.escape(targetName)}"]`);if(!target)return false;target.hidden=false;target.classList.remove('window-minimized');$$('.window').forEach(x=>x.classList.remove('window-active'));target.classList.add('window-active');target.scrollIntoView({behavior:'smooth',block:'center'});$$('.task-app').forEach(x=>x.classList.toggle('active',x.dataset.target===targetName));let p=APP_PROGRESS.get(targetName)||0;if(p<100){p=Math.max(p,10);setProgress(target,p,'starting');const timer=setInterval(()=>{p=Math.min(100,p+20);APP_PROGRESS.set(targetName,p);setProgress(target,p,p>=100?'ready':'running');if(p>=100){clearInterval(timer);if(targetName==='terminal')setTimeout(()=>$('#terminalInput')?.focus(),30);}},120);}else{setProgress(target,100,'ready');if(targetName==='terminal')setTimeout(()=>$('#terminalInput')?.focus(),30);}return true;}
function powerToggle(){desktop?.classList.toggle('power-suspended');}
function handleWindowControl(button){const win=button.closest('.window');if(!win)return false;const controls=[...button.parentElement.children],index=controls.indexOf(button);if(index===0||index===2){win.classList.add('window-minimized');win.hidden=true;}else if(index===1)win.classList.toggle('window-maximized');return true;}
function updateAuroraBoot(progress,state,stage){const fill=$('#auroraBootFill'),percent=$('#auroraBootPercent'),stageEl=$('#auroraBootStage'),pill=$('#auroraBootPill');if(!fill)return;const p=Math.max(0,Math.min(100,Number(progress)||0));fill.style.width=`${p}%`;percent.textContent=`${Math.round(p)}%`;stageEl.textContent=stage||'Initializing Spitfire';pill.textContent=state||(p>=100?'READY':'RUNNING');pill.classList.toggle('cyan',p<100);$('#auroraBootProgress')?.setAttribute('aria-valuenow',String(Math.round(p)));$$('#auroraBootStages li').forEach((li,i)=>{const threshold=Number(li.dataset.progress);li.classList.toggle('complete',p>=threshold);li.classList.toggle('active',p<threshold&&(i===0||p>=Number($$('#auroraBootStages li')[i-1]?.dataset.progress||0)));});}
function renderBootProgress(boot){const raw=Number(boot.progress_percent??boot.progress??0),progress=Number.isFinite(raw)?raw:0;let stage=boot.stage||boot.current_stage||boot.message;for(const [threshold,name] of BOOT_STAGES){if(progress<=threshold){stage=stage||name;break;}}const state=String(boot.state||boot.status||(progress>=100?'READY':'RUNNING')).toUpperCase();updateAuroraBoot(progress,state,stage);const bootWindow=$('[data-window="aurora-boot"]');if(bootWindow)setProgress(bootWindow,progress,progress>=100?'ready':'running');const auroraPill=$('#auroraPill');if(auroraPill){auroraPill.textContent=progress>=100?'READY':'STARTING';auroraPill.classList.toggle('cyan',progress<100);}const aurora=$('#aurora');if(aurora)aurora.textContent=progress>=100?'wayland: READY':`wayland: waiting for boot (${Math.round(progress)}%)`;}
function printTerminal(text){const out=$('#terminalOutput');if(!out)return;const line=document.createElement('div');line.textContent=String(text);out.appendChild(line);out.scrollTop=out.scrollHeight;}
function terminalCommand(raw){const command=String(raw??'').trim();if(!command)return;if(history[history.length-1]!==command)history.push(command);historyIndex=history.length;printTerminal(`chimera@aurora:~$ ${command}`);const [verb,...rest]=command.split(/\s+/),arg=rest.join(' ');switch(verb.toLowerCase()){case'help':printTerminal('Commands: help clear pwd ls whoami uname date echo aurora chimera kernel boot services jasper open <app> launch <app> refresh');break;case'clear':$('#terminalOutput')?.replaceChildren();break;case'pwd':printTerminal('/home/chimera');break;case'ls':printTerminal('Desktop  Documents  Downloads  Projects  System  Workspaces');break;case'whoami':printTerminal('chimera');break;case'uname':printTerminal('Chimera II OS / Aurora Wayland / Koronos');break;case'date':printTerminal(new Date().toString());break;case'echo':printTerminal(arg);break;case'aurora':activateWindow('aurora');printTerminal('Aurora Wayland: READY');break;case'chimera':activateWindow('system');printTerminal('Chimera II OS: ONLINE');break;case'kernel':activateWindow('kernel');printTerminal('Koronos kernel: RUNNING');break;case'boot':activateWindow('aurora-boot');printTerminal('Spitfire/Aurora boot monitor opened.');break;case'services':activateWindow('services');printTerminal('System services window opened.');break;case'jasper':activateWindow('jasper');printTerminal('Jasper Desktop Manager opened.');break;case'refresh':refresh();printTerminal('Desktop state refreshed.');break;case'open':case'launch':if(activateWindow(arg))printTerminal(`${arg}: opened`);else printTerminal(`Unknown application: ${arg}`);break;default:if(activateWindow(verb))printTerminal(`${verb}: opened`);else printTerminal(`Command not found: ${verb}. Type help.`)}}
document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const control=target.closest('.window-controls button');if(control){event.preventDefault();event.stopPropagation();handleWindowControl(control);return;}const task=target.closest('.task-app');if(task){event.preventDefault();activateWindow(task.dataset.target);return;}const pinned=target.closest('.pinned button[data-app]');if(pinned){event.preventDefault();activateWindow(pinned.dataset.app);toggleStart(false);return;}const all=target.closest('.start-heading .text-button');if(all){event.preventDefault();toggleStart(false);activateWindow('services');return;}const power=target.closest('.start-footer button[aria-label="Power"]');if(power){event.preventDefault();toggleStart(false);powerToggle();return;}if(target.closest('#startButton,#brand')){event.preventDefault();toggleStart();return;}if(target.closest('#searchButton')){event.preventDefault();toggleStart(true);$('#startSearch')?.focus();return;}if(target.closest('#refreshButton')){event.preventDefault();refresh();return;}const launcher=target.closest('[data-launch-app]');if(launcher){event.preventDefault();activateWindow(launcher.dataset.launchApp);return;}});
document.addEventListener('pointerdown',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;if(!startMenu?.contains(target)&&!$('#startButton')?.contains(target)&&!$('#brand')?.contains(target))toggleStart(false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){toggleStart(false);return;}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();toggleStart(true);$('#startSearch')?.focus();return;}const ti=$('#terminalInput');if(document.activeElement===ti){if(e.key==='ArrowUp'){e.preventDefault();historyIndex=Math.max(0,historyIndex-1);ti.value=history[historyIndex]||'';return;}if(e.key==='ArrowDown'){e.preventDefault();historyIndex=Math.min(history.length,historyIndex+1);ti.value=history[historyIndex]||'';return;}}const isEnter=e.key==='Enter';if(!isEnter)return;const active=document.activeElement;if(active instanceof HTMLInputElement&&active.id==='startSearch'){e.preventDefault();if(active.value.trim()){executeCommand(active.value);toggleStart(false);}return;}if(active instanceof HTMLButtonElement){e.preventDefault();active.click();}});
$('#terminalForm')?.addEventListener('submit',e=>{e.preventDefault();const input=$('#terminalInput');terminalCommand(input.value);input.value='';});
function executeCommand(raw){const command=String(raw||'').trim();if(!command)return false;const parts=command.split(/\s+/),verb=parts.shift().toLowerCase(),argument=parts.join(' ');if(verb==='help'||verb==='?'){activateWindow('system');return true;}if(verb==='refresh'||verb==='reload'){refresh();return true;}if(verb==='power'||verb==='suspend'){powerToggle();return true;}if(['open','launch','show','start','app'].includes(verb))return activateWindow(argument);return activateWindow(command);}
function updateClock(){const now=new Date(),t=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#clock').textContent=t;$('#trayClock').textContent=t;}setInterval(updateClock,1000);updateClock();
async function getJSON(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json();}
async function refresh(){const health=await getJSON('/api/health').catch(()=>({ok:false}));$('#health').textContent=health.ok?'Python runtime online':'Python runtime offline';$('#healthDot').classList.toggle('online',Boolean(health.ok));const state=await getJSON('/api/state').catch(e=>({error:e.message}));if(state.error)return;const boot=state.boot||{};renderBootProgress(boot);$('#boot').textContent=JSON.stringify(boot,null,2);$('#kernel').textContent=JSON.stringify(state.kernel,null,2);$('#bootPill').textContent=`${boot.progress_percent??0}%`;const jasper=state.jasper||{};$('#jasper').textContent=`Manager: ${jasper.manager||'Jasper'} | State: ${jasper.state||'unknown'} | Desktop: ${jasper.desktop_state||'unknown'} | Profile: ${jasper.profile||'aurora'} | Services: ${jasper.required_services_ready||0}/${jasper.required_services_total||0}`;$('#jasperPill').textContent=String(jasper.state||'UNKNOWN').toUpperCase();const aurora=state.aurora||{},bootComplete=Number(boot.progress_percent??0)>=100;$('#aurora').textContent=bootComplete?`${aurora.mode||'wayland'}: ${aurora.state||'READY'}`:`${aurora.mode||'wayland'}: waiting for boot completion`;$('#auroraPill').textContent=bootComplete?String(aurora.state||'READY').toUpperCase():'STARTING';const services=$('#services');if(services){services.replaceChildren();Object.entries(state.services||{}).forEach(([name,value])=>{const item=document.createElement('article');item.className='service';const title=document.createElement('b');title.textContent=name;const status=document.createElement('small');status.textContent=String(value.state||'unknown');item.append(title,status);services.appendChild(item);});}}
refresh();setInterval(refresh,2000);
const demo=$('#interactionDemo');demo?.addEventListener('pointermove',e=>{const r=demo.getBoundingClientRect();demo.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);demo.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`);$('#pointerReadout').textContent=`${Math.round(e.clientX)}, ${Math.round(e.clientY)}`;});demo?.addEventListener('pointerleave',()=>{demo.style.setProperty('--mx','50%');demo.style.setProperty('--my','50%');});
const snapPreview=$('#snapPreview');desktop?.addEventListener('pointermove',e=>{const edge=34,w=innerWidth,h=innerHeight;let zone=null;if(e.clientX<edge)zone={x:12,y:72,width:w/2-18,height:h-150};else if(e.clientX>w-edge)zone={x:w/2+6,y:72,width:w/2-18,height:h-150};else if(e.clientY<edge)zone={x:12,y:72,width:w-24,height:h/2-45};if(zone)Object.assign(snapPreview.style,{left:`${zone.x}px`,top:`${zone.y}px`,width:`${zone.width}px`,height:`${zone.height}px`,opacity:1});else snapPreview.style.opacity=0;});desktop?.addEventListener('pointerleave',()=>{snapPreview.style.opacity=0;});
$('#startSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();$$('.pinned button').forEach(btn=>{btn.hidden=Boolean(q&&!btn.textContent.toLowerCase().includes(q));});});
if(matchMedia('(prefers-reduced-motion: reduce)').matches)document.documentElement.classList.add('reduce-motion');