const $ = (q, root = document) => root.querySelector(q);
const $$ = (q, root = document) => [...root.querySelectorAll(q)];
const desktop = $('#desktop');
const startMenu = $('#startMenu');
const APP_TARGETS = { system:'system', jasper:'jasper', terminal:'services', research:'kernel', files:'services', network:'services', settings:'system', services:'services', boot:'boot', kernel:'kernel', aurora:'aurora' };
function toggleStart(force) { if (!startMenu) return; const open = force ?? !startMenu.classList.contains('open'); startMenu.classList.toggle('open', open); startMenu.setAttribute('aria-hidden', String(!open)); if (open) setTimeout(() => $('#startSearch')?.focus(), 60); }
function activateWindow(name) { const raw = String(name || '').trim().toLowerCase(); const targetName = APP_TARGETS[raw] || raw; if (!targetName) return false; const target = document.querySelector(`[data-window="${CSS.escape(targetName)}"]`); if (!target) return false; target.hidden = false; target.classList.remove('window-minimized'); target.scrollIntoView({behavior:'smooth',block:'center'}); $$('.task-app').forEach(x => x.classList.toggle('active', x.dataset.target === targetName)); return true; }
function powerToggle() { desktop?.classList.toggle('power-suspended'); }
function handleWindowControl(button) { const win = button.closest('.window'); if (!win) return false; const controls = [...button.parentElement.children]; const index = controls.indexOf(button); if (index === 0 || index === 2) { win.classList.add('window-minimized'); win.hidden = true; } else if (index === 1) win.classList.toggle('window-maximized'); return true; }
function executeCommand(raw) { const command = String(raw ?? '').trim(); if (!command) return false; const parts = command.split(/\s+/); const verb = parts.shift().toLowerCase(); const argument = parts.join(' '); if (verb === 'help' || verb === '?') return activateWindow('system'); if (verb === 'refresh' || verb === 'reload') { refresh(); return true; } if (verb === 'power' || verb === 'suspend') { powerToggle(); return true; } if (verb === 'open' || verb === 'launch' || verb === 'show' || verb === 'start' || verb === 'app') return activateWindow(argument); return activateWindow(command); }
document.addEventListener('click', event => { const target = event.target instanceof Element ? event.target : null; if (!target) return; const windowControl = target.closest('.window-controls button'); if (windowControl) { event.preventDefault(); event.stopPropagation(); handleWindowControl(windowControl); return; } const taskApp = target.closest('.task-app'); if (taskApp) { event.preventDefault(); activateWindow(taskApp.dataset.target); return; } const pinned = target.closest('.pinned button[data-app]'); if (pinned) { event.preventDefault(); activateWindow(pinned.dataset.app); toggleStart(false); return; } const allApps = target.closest('.start-heading .text-button'); if (allApps) { event.preventDefault(); toggleStart(false); activateWindow('services'); return; } const power = target.closest('.start-footer button[aria-label="Power"]'); if (power) { event.preventDefault(); toggleStart(false); powerToggle(); return; } if (target.closest('#startButton, #brand')) { event.preventDefault(); toggleStart(); return; } if (target.closest('#searchButton')) { event.preventDefault(); toggleStart(true); $('#startSearch')?.focus(); return; } if (target.closest('#refreshButton')) { event.preventDefault(); refresh(); } });
document.addEventListener('pointerdown', event => { const target = event.target instanceof Element ? event.target : null; if (!target) return; if (!startMenu?.contains(target) && !$('#startButton')?.contains(target) && !$('#brand')?.contains(target)) toggleStart(false); });
document.addEventListener('keydown', e => { if (e.key === 'Escape') { toggleStart(false); return; } if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); toggleStart(true); $('#startSearch')?.focus(); return; } if (e.key !== 'Enter') return; const active = document.activeElement; if (active instanceof HTMLInputElement && active.id === 'startSearch') { e.preventDefault(); if (active.value.trim()) { executeCommand(active.value); toggleStart(false); } else { $$('.pinned button[data-app]').find(btn => !btn.hidden)?.click(); } return; } if (active instanceof HTMLButtonElement) { e.preventDefault(); active.click(); } });
function updateClock() { const now = new Date(); const t = now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); $('#clock').textContent=t; $('#trayClock').textContent=t; }
setInterval(updateClock,1000); updateClock();
async function getJSON(path) { const r=await fetch(path,{cache:'no-store'}); if(!r.ok) throw new Error(`${r.status} ${r.statusText}`); return r.json(); }
async function refresh() { const health=await getJSON('/api/health').catch(()=>({ok:false})); $('#health').textContent=health.ok?'Python runtime online':'Python runtime offline'; $('#healthDot').classList.toggle('online',Boolean(health.ok)); const state=await getJSON('/api/state').catch(e=>({error:e.message})); if(state.error)return; const boot=state.boot||{}; $('#boot').textContent=JSON.stringify(boot,null,2); $('#kernel').textContent=JSON.stringify(state.kernel,null,2); $('#bootPill').textContent=`${boot.progress_percent??0}%`; const jasper=state.jasper||{}; $('#jasper').textContent=`Manager: ${jasper.manager||'Jasper'} | State: ${jasper.state||'unknown'} | Desktop: ${jasper.desktop_state||'unknown'} | Profile: ${jasper.profile||'aurora'} | Services: ${jasper.required_services_ready||0}/${jasper.required_services_total||0}`; $('#jasperPill').textContent=String(jasper.state||'UNKNOWN').toUpperCase(); $('#aurora').textContent=`${state.aurora.mode}: ${state.aurora.state}`; $('#auroraPill').textContent=String(state.aurora.state||'READY').toUpperCase(); const services=$('#services'); services.replaceChildren(); Object.entries(state.services||{}).forEach(([name,value])=>{const item=document.createElement('article');item.className='service';const title=document.createElement('b');title.textContent=name;const status=document.createElement('small');status.textContent=String(value.state||'unknown');item.append(title,status);services.appendChild(item);}); }
refresh(); setInterval(refresh,2000);
const demo=$('#interactionDemo'); demo?.addEventListener('pointermove',e=>{const r=demo.getBoundingClientRect();demo.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);demo.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`);$('#pointerReadout').textContent=`${Math.round(e.clientX)}, ${Math.round(e.clientY)}`;}); demo?.addEventListener('pointerleave',()=>{demo.style.setProperty('--mx','50%');demo.style.setProperty('--my','50%');});
const snapPreview=$('#snapPreview'); desktop?.addEventListener('pointermove',e=>{const edge=34,w=innerWidth,h=innerHeight;let zone=null;if(e.clientX<edge)zone={x:12,y:72,width:w/2-18,height:h-150};else if(e.clientX>w-edge)zone={x:w/2+6,y:72,width:w/2-18,height:h-150};else if(e.clientY<edge)zone={x:12,y:72,width:w-24,height:h/2-45};if(zone)Object.assign(snapPreview.style,{left:`${zone.x}px`,top:`${zone.y}px`,width:`${zone.width}px`,height:`${zone.height}px`,opacity:1});else snapPreview.style.opacity=0;}); desktop?.addEventListener('pointerleave',()=>{snapPreview.style.opacity=0;});
$('#startSearch')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();$$('.pinned button').forEach(btn=>{btn.hidden=Boolean(q&&!btn.textContent.toLowerCase().includes(q));});});
if(matchMedia('(prefers-reduced-motion: reduce)').matches)document.documentElement.classList.add('reduce-motion');