(()=>{'use strict';
const fallback={categories:[{id:'system',title:'System',apps:[{id:'terminal',title:'Terminal',icon:'⌘',target:'#terminal'},{id:'system',title:'System',icon:'◈',target:'[data-window=system]'},{id:'files',title:'Files',icon:'▣',target:'[data-window=services]'},{id:'monitor',title:'System Monitor',icon:'▥',target:'[data-window=services]'}]},{id:'browsers',title:'Web Browsers',apps:[{id:'firefox',title:'Firefox',icon:'🦊',url:'https://www.mozilla.org/firefox/',mode:'external'},{id:'chrome',title:'Google Chrome',icon:'🌐',url:'https://www.google.com/chrome/',mode:'external'}]},{id:'security',title:'Security Research',apps:[{id:'burp',title:'Burp Suite Community Edition',icon:'🛡',url:'https://portswigger.net/burp/communitydownload',mode:'external-docs'},{id:'metasploit',title:'Metasploit Framework',icon:'◆',url:'https://docs.metasploit.com/',mode:'external-docs'},{id:'kali',title:'Kali Tools Catalog',icon:'K',url:'https://www.kali.org/tools/',mode:'external-catalog'}]}]};
let registry=fallback;
const flatten=()=>registry.categories.flatMap(c=>c.apps.map(a=>({...a,category:c.title})));
const openApp=app=>{if(!app)return;if(app.url){const w=window.open(app.url,'chimera-app-'+app.id,'noopener,noreferrer');if(!w)location.href=app.url;return}const u=new URL(location.href);u.hash='app='+encodeURIComponent(app.id);const w=window.open(u.href,'chimera-'+app.id,'noopener,noreferrer');if(!w)location.href=u.href};
const focusApp=id=>{const app=flatten().find(a=>a.id===id);if(!app)return;const el=document.querySelector(app.target||'#workspace');el?.scrollIntoView({behavior:'smooth',block:'center'});document.querySelectorAll('.window').forEach(x=>x.classList.remove('window-active'));el?.classList.add('window-active')};
function build(){if(document.querySelector('.aurora-shell-dock'))return;const dock=document.createElement('aside');dock.className='aurora-shell-dock glass';dock.setAttribute('aria-label','Aurora application dock');dock.innerHTML='<div class="aurora-shell-logo">✦</div>'+flatten().slice(0,11).map(a=>`<button data-aurora-app="${a.id}" title="${a.title}"><span>${a.icon}</span></button>`).join('')+'<button data-aurora-menu="1" title="All applications"><span>⋮⋮</span></button>';document.body.append(dock);
const rail=document.createElement('aside');rail.className='aurora-shell-widgets glass';rail.innerHTML='<strong>AURORA</strong><span>WAYLAND</span><hr><b id="asClock">--:--</b><small>CHIMERA II OS</small><div class="as-meter"><i id="asCpu"></i></div><small>CPU / virtual runtime</small><div class="as-meter"><i id="asMem"></i></div><small>Memory fabric</small><div class="as-status">GLASS SESSION · ONLINE</div>';document.body.append(rail);
const menu=document.createElement('section');menu.className='aurora-app-center glass';menu.hidden=true;menu.innerHTML='<header><strong>All Applications</strong><button data-close-apps>×</button></header><input data-app-search placeholder="Search applications…" autocomplete="off">'+registry.categories.map(c=>`<div class="aurora-app-group" data-group="${c.id}"><h3>${c.title}</h3><div class="aurora-app-grid">${c.apps.map(a=>`<button data-center-app="${a.id}" title="${a.note||a.title}"><span>${a.icon}</span><b>${a.title}</b><small>${a.mode||'native-web'}</small></button>`).join('')}</div></div>`).join('');document.body.append(menu);
dock.addEventListener('click',e=>{const b=e.target.closest('[data-aurora-app]');if(b)openApp(flatten().find(a=>a.id===b.dataset.auroraApp));const m=e.target.closest('[data-aurora-menu]');if(m)menu.hidden=!menu.hidden});menu.addEventListener('click',e=>{const b=e.target.closest('[data-center-app]');if(b){openApp(flatten().find(a=>a.id===b.dataset.centerApp));menu.hidden=true}if(e.target.closest('[data-close-apps]'))menu.hidden=true});menu.querySelector('[data-app-search]').addEventListener('input',e=>{const q=e.target.value.toLowerCase();menu.querySelectorAll('[data-center-app]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));menu.querySelectorAll('.aurora-app-group').forEach(g=>g.hidden=[...g.querySelectorAll('[data-center-app]')].every(b=>b.hidden))});
setInterval(()=>{const d=new Date(),c=document.querySelector('#asClock');if(c)c.textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const cpu=document.querySelector('#asCpu'),mem=document.querySelector('#asMem');if(cpu)cpu.style.width=(10+Math.random()*30)+'%';if(mem)mem.style.width=(18+Math.random()*28)+'%'},1000)}
async function init(){try{const r=await fetch('/aurora_apps.json',{cache:'no-store'});if(r.ok){const x=await r.json();if(x?.categories)registry=x}}catch{}build();const id=new URLSearchParams(location.hash.slice(1)).get('app');if(id)setTimeout(()=>focusApp(id),120)}init();window.addEventListener('hashchange',()=>focusApp(new URLSearchParams(location.hash.slice(1)).get('app')));
})();